name: hello_world
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0          # Dart 3.8.x
  flutter: ">=3.16.0"  # Probado en Flutter 3.16 → 3.22

# ────────────────────────────────────
#               DEPENDENCIAS
# ────────────────────────────────────
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter            # gen_l10n

  # UI / Componentes
  cupertino_icons:   ^1.0.8
  google_nav_bar:    ^5.0.6
  flutter_spinkit:   ^5.2.0
  quickalert:        ^1.0.1
  comment_box:       ^0.0.18
  appwrite: ^17.0.0
  # Manejo de estado / Hooks
  flutter_riverpod:  ^2.5.1
  hooks_riverpod:    ^2.5.1    # HookConsumerWidget, etc.
  flutter_hooks: ^0.21.2
  equatable:         ^2.0.5    # ==/hashCode para estados

  # Networking
  dio:              ^5.4.0
  dio_smart_retry: ^7.0.1
  stack_trace:      ^1.11.0

  # Geolocalización / Mapas
  geolocator: ^14.0.1
  flutter_map: ^8.1.1
  latlong2:     ^0.9.0

  # Persistencia y seguridad
  shared_preferences:     ^2.2.2
  flutter_secure_storage: ^10.0.0-beta.4   # requiere minSdk 21 en Android
  path_provider:          ^2.1.3

  # Funcionalidades varias
  wakelock_plus:    ^1.2.7
  flutter_tts: ^4.2.2
  email_validator: ^3.0.0
  screenshot: ^3.0.0
  image_picker:     ^1.0.7
  image_cropper: ^9.1.0
  share_plus: ^11.0.0
  image:            ^4.0.17

  # Charts
  fl_chart: ^1.0.0

  # Internacionalización
  intl: ^0.20.2

# ────────────────────────────────────
#         DEPENDENCIAS DE DESARROLLO
# ────────────────────────────────────
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:  ^2.4.9
  coverage:      ^1.6.3   # reportes LCOV
  mockito:       ^5.4.2   # mocks en tests

# ────────────────────────────────────
#               FLUTTER
# ────────────────────────────────────
flutter:
  uses-material-design: true
  generate: true         # habilita gen_l10n